FROM node:20.16.0-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

FROM node:20.16.0-alpine

WORKDIR /app

COPY --from=build /app .

VOLUME [ "/uploads", "/src/uploads/" ]

EXPOSE 5000

CMD ["npm", "start"]